# Generated by Django 2.1.7 on 2019-04-26 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0002_auto_20190423_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='author',
        ),
        migrations.DeleteModel(
            name='item',
        ),
    ]
